'use strict';
const width = 160;
const height = 170;
const area = width * height;
console.log('the value of area', area);
console.log('the type of area', typeof area);
const bill = 100;
const payment = 120;
const change = payment - bill;
console.log('the value of change', change);
console.log('the type of change', typeof change);
const quizzes = 10;
const midterm = 9;
const final = 10;
const grade = (quizzes + midterm + final) / 3;
console.log('the value of grade', grade);
console.log('the type of grade', typeof grade);
const firstName = 'YUHAN';
const lastName = 'ZHANG';
const fullName = firstName + ' ' + lastName;
console.log('the value of fullName', fullName);
console.log('the type of fullName', typeof fullName);
const pH = 7;
const isAcidic = pH < 7;
console.log('the value of isAcidic', isAcidic);
console.log('the type of isAcidic', typeof isAcidic);
const headCount = 11;
const isSparta = headCount === 300;
console.log('the value of isSparta', isSparta);
console.log('the type of isSparta', typeof isSparta);
let motto = fullName;
motto = fullName + ' is the GOAT';
console.log('the value of motto', motto);
console.log('the type of motto', typeof motto);
